kafka:
  consumer:
     zookeeperConnect: 192.168.222.128:2181
     servers: 192.168.222.128:9092
     enableAutoCommit: true
     sessionTimeout: 6000
     autoCommitInterval: 100
     autoOffsetReset: latest
     topic: test
     groupId: test
     concurrency: 10
  producer:
     servers: 192.168.222.128:9092
     retries: 0
     batchSize: 4096
     linger: 1
     bufferMemory: 40960